var gameOverCard =
{
    "Id": 0,
    "CasinoId": 0,
    "CasinoName": "Game Over",
    "CasinoColor": "Game Over",
    "LotLocation": "Game Over",
    "LotId": 0,
    "StartingMoney": 0,
    "DiceFace": 0,
    "Message": "Pay the Strip"
}



var vegasCards = [
    {
        "Id": 1,
        "CasinoId": 1,
        "CasinoName": "The Strip",
        "CasinoColor": "Strip",
        "LotLocation": "A6",
        "LotId": 6,
        "StartingMoney": 4,
        "DiceFace": 6,
        "Message": "Pay the Strip"
    },
    {
        "Id": 2,
        "CasinoId": 1,
        "CasinoName": "The Strip",
        "CasinoColor": "Strip",
        "LotLocation": "D5",
        "LotId": 29,
        "StartingMoney": 9,
        "DiceFace": 1,
        "Message": "Pay the Strip"
    },
    {
        "Id": 3,
        "CasinoId": 1,
        "CasinoName": "The Strip",
        "CasinoColor": "Strip",
        "LotLocation": "F8",
        "LotId": 47,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay the Strip"
    },
    {
        "Id": 4,
        "CasinoId": 2,
        "CasinoName": "Albion",
        "CasinoColor": "Purple",
        "LotLocation": "A2",
        "LotId": 2,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay Purple Casinos"
    },
    {
        "Id": 5,
        "CasinoId": 2,
        "CasinoName": "Albion",
        "CasinoColor": "Purple",
        "LotLocation": "B3",
        "LotId": 9,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Purple Casinos"
    },
    {
        "Id": 6,
        "CasinoId": 2,
        "CasinoName": "Albion",
        "CasinoColor": "Purple",
        "LotLocation": "B4",
        "LotId": 10,
        "StartingMoney": 4,
        "DiceFace": 6,
        "Message": "Pay Purple Casinos"
    },
    {
        "Id": 7,
        "CasinoId": 2,
        "CasinoName": "Albion",
        "CasinoColor": "Purple",
        "LotLocation": "C8",
        "LotId": 24,
        "StartingMoney": 9,
        "DiceFace": 1,
        "Message": "Pay Purple Casinos"
    },
    {
        "Id": 8,
        "CasinoId": 2,
        "CasinoName": "Albion",
        "CasinoColor": "Purple",
        "LotLocation": "C3",
        "LotId": 24,
        "StartingMoney": 4,
        "DiceFace": 6,
        "Message": "Pay Purple Casinos"
    },
    {
        "Id": 9,
        "CasinoId": 2,
        "CasinoName": "Albion",
        "CasinoColor": "Purple",
        "LotLocation": "D7",
        "LotId": 31,
        "StartingMoney": 5,
        "DiceFace": 5,
        "Message": "Pay Purple Casinos"
    },
    {
        "Id": 10,
        "CasinoId": 2,
        "CasinoName": "Albion",
        "CasinoColor": "Purple",
        "LotLocation": "D6",
        "LotId": 30,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay Purple Casinos"
    },
    {
        "Id": 11,
        "CasinoId": 2,
        "CasinoName": "Albion",
        "CasinoColor": "Purple",
        "LotLocation": "E2",
        "LotId": 35,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay Purple Casinos"
    },
    {
        "Id": 12,
        "CasinoId": 2,
        "CasinoName": "Albion",
        "CasinoColor": "Purple",
        "LotLocation": "F1",
        "LotId": 40,
        "StartingMoney": 4,
        "DiceFace": 6,
        "Message": "Pay Purple Casinos"
    },
    {
        "Id": 13,
        "CasinoId": 3,
        "CasinoName": "Pioneer",
        "CasinoColor": "Brown",
        "LotLocation": "A1",
        "LotId": 1,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Brown Casinos"
    },
    {
        "Id": 14,
        "CasinoId": 3,
        "CasinoName": "Pioneer",
        "CasinoColor": "Brown",
        "LotLocation": "B6",
        "LotId": 12,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Brown Casinos"
    },
    {
        "Id": 15,
        "CasinoId": 3,
        "CasinoName": "Pioneer",
        "CasinoColor": "Brown",
        "LotLocation": "C4",
        "LotId": 24,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay Brown Casinos"
    },
    {
        "Id": 16,
        "CasinoId": 3,
        "CasinoName": "Pioneer",
        "CasinoColor": "Brown",
        "LotLocation": "C9",
        "LotId": 24,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Brown Casinos"
    },
    {
        "Id": 17,
        "CasinoId": 3,
        "CasinoName": "Pioneer",
        "CasinoColor": "Brown",
        "LotLocation": "D9",
        "LotId": 33,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Brown Casinos"
    },
    {
        "Id": 18,
        "CasinoId": 3,
        "CasinoName": "Pioneer",
        "CasinoColor": "Brown",
        "LotLocation": "D2",
        "LotId": 26,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Brown Casinos"
    },
    {
        "Id": 19,
        "CasinoId": 3,
        "CasinoName": "Pioneer",
        "CasinoColor": "Brown",
        "LotLocation": "E1",
        "LotId": 34,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Brown Casinos"
    },
    {
        "Id": 20,
        "CasinoId": 3,
        "CasinoName": "Pioneer",
        "CasinoColor": "Brown",
        "LotLocation": "E5",
        "LotId": 38,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Brown Casinos"
    },
    {
        "Id": 21,
        "CasinoId": 3,
        "CasinoName": "Pioneer",
        "CasinoColor": "Brown",
        "LotLocation": "F5",
        "LotId": 44,
        "StartingMoney": 9,
        "DiceFace": 1,
        "Message": "Pay Brown Casinos"
    },
    {
        "Id": 22,
        "CasinoId": 4,
        "CasinoName": "Vega",
        "CasinoColor": "Aqua",
        "LotLocation": "D4",
        "LotId": 28,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Aqua Casinos"
    },
    {
        "Id": 23,
        "CasinoId": 4,
        "CasinoName": "Vega",
        "CasinoColor": "Aqua",
        "LotLocation": "D3",
        "LotId": 27,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Aqua Casinos"
    },
    {
        "Id": 24,
        "CasinoId": 4,
        "CasinoName": "Vega",
        "CasinoColor": "Aqua",
        "LotLocation": "C10",
        "LotId": 13,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Aqua Casinos"
    },
    {
        "Id": 25,
        "CasinoId": 4,
        "CasinoName": "Vega",
        "CasinoColor": "Aqua",
        "LotLocation": "C5",
        "LotId": 24,
        "StartingMoney": 9,
        "DiceFace": 1,
        "Message": "Pay Aqua Casinos"
    },
    {
        "Id": 26,
        "CasinoId": 4,
        "CasinoName": "Vega",
        "CasinoColor": "Aqua",
        "LotLocation": "F7",
        "LotId": 46,
        "StartingMoney": 5,
        "DiceFace": 5,
        "Message": "Pay Aqua Casinos"
    },
    {
        "Id": 27,
        "CasinoId": 4,
        "CasinoName": "Vega",
        "CasinoColor": "Aqua",
        "LotLocation": "F6",
        "LotId": 45,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay Aqua Casinos"
    },
    {
        "Id": 28,
        "CasinoId": 4,
        "CasinoName": "Vega",
        "CasinoColor": "Aqua",
        "LotLocation": "A3",
        "LotId": 3,
        "StartingMoney": 5,
        "DiceFace": 5,
        "Message": "Pay Aqua Casinos"
    },
    {
        "Id": 29,
        "CasinoId": 4,
        "CasinoName": "Vega",
        "CasinoColor": "Aqua",
        "LotLocation": "E3",
        "LotId": 36,
        "StartingMoney": 5,
        "DiceFace": 5,
        "Message": "Pay Aqua Casinos"
    },
    {
        "Id": 30,
        "CasinoId": 4,
        "CasinoName": "Vega",
        "CasinoColor": "Aqua",
        "LotLocation": "B5",
        "LotId": 11,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Aqua Casinos"
    },
    {
        "Id": 31,
        "CasinoId": 5,
        "CasinoName": "Tivoli",
        "CasinoColor": "Silver",
        "LotLocation": "D1",
        "LotId": 25,
        "StartingMoney": 4,
        "DiceFace": 6,
        "Message": "Pay Silver Casinos"
    },
    {
        "Id": 32,
        "CasinoId": 5,
        "CasinoName": "Tivoli",
        "CasinoColor": "Silver",
        "LotLocation": "C11",
        "LotId": 13,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay Silver Casinos"
    },
    {
        "Id": 33,
        "CasinoId": 5,
        "CasinoName": "Tivoli",
        "CasinoColor": "Silver",
        "LotLocation": "C6",
        "LotId": 24,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Silver Casinos"
    },
    {
        "Id": 34,
        "CasinoId": 5,
        "CasinoName": "Tivoli",
        "CasinoColor": "Silver",
        "LotLocation": "C1",
        "LotId": 13,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Silver Casinos"
    },
    {
        "Id": 35,
        "CasinoId": 5,
        "CasinoName": "Tivoli",
        "CasinoColor": "Silver",
        "LotLocation": "F9",
        "LotId": 48,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Silver Casinos"
    },
    {
        "Id": 36,
        "CasinoId": 5,
        "CasinoName": "Tivoli",
        "CasinoColor": "Silver",
        "LotLocation": "F2",
        "LotId": 41,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Silver Casinos"
    },
    {
        "Id": 37,
        "CasinoId": 5,
        "CasinoName": "Tivoli",
        "CasinoColor": "Silver",
        "LotLocation": "A5",
        "LotId": 5,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Silver Casinos"
    },
    {
        "Id": 38,
        "CasinoId": 5,
        "CasinoName": "Tivoli",
        "CasinoColor": "Silver",
        "LotLocation": "E4",
        "LotId": 37,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Silver Casinos"
    },
    {
        "Id": 39,
        "CasinoId": 5,
        "CasinoName": "Tivoli",
        "CasinoColor": "Silver",
        "LotLocation": "B2",
        "LotId": 8,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay Silver Casinos"
    },
    {
        "Id": 40,
        "CasinoId": 6,
        "CasinoName": "Sphinx",
        "CasinoColor": "Gold",
        "LotLocation": "A4",
        "LotId": 4,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Gold Casinos"
    },
    {
        "Id": 41,
        "CasinoId": 6,
        "CasinoName": "Sphinx",
        "CasinoColor": "Gold",
        "LotLocation": "B1",
        "LotId": 7,
        "StartingMoney": 5,
        "DiceFace": 5,
        "Message": "Pay Gold Casinos"
    },
    {
        "Id": 42,
        "CasinoId": 6,
        "CasinoName": "Sphinx",
        "CasinoColor": "Gold",
        "LotLocation": "C2",
        "LotId": 24,
        "StartingMoney": 7,
        "DiceFace": 3,
        "Message": "Pay Gold Casinos"
    },
    {
        "Id": 43,
        "CasinoId": 6,
        "CasinoName": "Sphinx",
        "CasinoColor": "Gold",
        "LotLocation": "C7",
        "LotId": 24,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay Gold Casinos"
    },
    {
        "Id": 44,
        "CasinoId": 6,
        "CasinoName": "Sphinx",
        "CasinoColor": "Gold",
        "LotLocation": "C12",
        "LotId": 24,
        "StartingMoney": 5,
        "DiceFace": 5,
        "Message": "Pay Gold Casinos"
    },
    {
        "Id": 45,
        "CasinoId": 6,
        "CasinoName": "Sphinx",
        "CasinoColor": "Gold",
        "LotLocation": "D8",
        "LotId": 32,
        "StartingMoney": 8,
        "DiceFace": 2,
        "Message": "Pay Gold Casinos"
    },
    {
        "Id": 46,
        "CasinoId": 6,
        "CasinoName": "Sphinx",
        "CasinoColor": "Gold",
        "LotLocation": "E6",
        "LotId": 39,
        "StartingMoney": 4,
        "DiceFace": 6,
        "Message": "Pay Gold Casinos"
    },
    {
        "Id": 47,
        "CasinoId": 6,
        "CasinoName": "Sphinx",
        "CasinoColor": "Gold",
        "LotLocation": "F4",
        "LotId": 43,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Gold Casinos"
    },
    {
        "Id": 48,
        "CasinoId": 6,
        "CasinoName": "Sphinx",
        "CasinoColor": "Gold",
        "LotLocation": "F3",
        "LotId": 42,
        "StartingMoney": 6,
        "DiceFace": 4,
        "Message": "Pay Gold Casinos"
    }
]