const voidSeederEventCards = [
    {
        "ID": 1,
        "Movers": [2,4,5],
        "Direction": 1,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Terror",
        "RealCardText": "Each Character draws cards from their Action deck until they have 5 cards in hand and then Scans all their Contamination cards. If they have at least 1 INFECTED result, increase their Insanity level to 5. Afterward, all Characters discard all cards from their hands.",
        "AppCardText": "Each Character draws cards from their Action deck until they have 5 cards in hand and then Scans all their Contamination cards. If they have at least 1 INFECTED result, increase their Insanity level to 5. Afterward, all Characters discard all cards from their hands.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 2,
        "Movers": [4,5],
        "Direction": 1,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Hunt",
        "RealCardText": "Each Void Seeder not in Combat moves to a neighboring Room containing a Character, if possible. If several Rooms are eligible, it moves to the Room with the lower number. Otherwise, it does not move.",
        "AppCardText": "Each Void Seeder not in Combat moves to a neighboring Room containing a Character, if possible. If several Rooms are eligible, it moves to the Room with the lower number. Otherwise, it does not move.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 3,
        "Movers": [3,4],
        "Direction": 1,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Tendrils",
        "RealCardText": "Every Character in a Room with Technical Corridors increses their Insanity Level.",
        "AppCardText": "Every Character in a Room with Technical Corridors increses their Insanity Level.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 4,
        "Movers": [3,4,5],
        "Direction": 2,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Computer System Failure",
        "RealCardText": "If there is a Malfunction marker in any Room with a Computer, place a Malfunction marker in each other Room with a Computer. Remove this card from the game and reshuffle the Event deck.",
        "AppCardText": "If there is a Malfunction marker in any Room with a Computer, place a Malfunction marker in each other Room with a Computer.",
        "RemoveAndReshuffleDeck": true,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 5,
        "Movers": [2,4,5],
        "Direction": 4,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Monophobia",
        "RealCardText": "Each Character alone in a Room and not in Combat resolves a Panic card.",
        "AppCardText": "Each Character alone in a Room and not in Combat resolves a Panic card.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 6,
        "Movers": [4,5],
        "Direction": 2,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Terror",
        "RealCardText": "Each Character draws cards from their Action deck until they have 5 cards in hand and then Scans all their Contamination cards. If they have at least 1 INFECTED result, increase their Insanity level to 5. Afterward, all Characters discard all cards from their hands.",
        "AppCardText": "Each Character draws cards from their Action deck until they have 5 cards in hand and then Scans all their Contamination cards. If they have at least 1 INFECTED result, increase their Insanity level to 5. Afterward, all Characters discard all cards from their hands.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 7,
        "Movers": [2,3],
        "Direction": 4,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Neurosis",
        "RealCardText": "Every Character in a Room with a Lair or in a Room neighboring a Lair draws a Panic card and resolves it.",
        "AppCardText": "Every Character in a Room with a Lair or in a Room neighboring a Lair draws a Panic card and resolves it.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 8,
        "Movers": [3,4],
        "Direction": 4,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Agoraphobia",
        "RealCardText": "If there is more than 1 Character in a Room, place a Despoiler in that Room. Do not Resolve a Surprise Attack. If there is more than 1 Room eligible it appears in the Room with the lower number.",
        "AppCardText": "If there is more than 1 Character in a Room, place a Despoiler in that Room. Do not Resolve a Surprise Attack. If there is more than 1 Room eligible it appears in the Room with the lower number.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 9,
        "Movers": [4,5],
        "Direction": 3,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Agoraphobia",
        "RealCardText": "If there is more than 1 Character in a Room, place a Despoiler in that Room. Do not Resolve a Surprise Attack. If there is more than 1 Room eligible it appears in the Room with the lower number.",
        "AppCardText": "If there is more than 1 Character in a Room, place a Despoiler in that Room. Do not Resolve a Surprise Attack. If there is more than 1 Room eligible it appears in the Room with the lower number.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 10,
        "Movers": [3,4,5],
        "Direction": 3,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Evacuation Pod Ejection",
        "RealCardText": "Remove the Escape pod token with the lower number. Remove this card from the game and reshuffle the Event deck (including the Discard Pile.)",
        "AppCardText": "Remove the Escape pod token with the lowest number.",
        "RemoveAndReshuffleDeck": true,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 11,
        "Movers": [2,3],
        "Direction": 4,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Fire Wave",
        "RealCardText": "Find the Room with the lower number containing a Fire marker. Place a Fire marker in each neighboring Room. Fire does not spread through Closed Doors of Technical Corridors.",
        "AppCardText": "Find the Room with the lower number containing a Fire marker. Place a Fire marker in each neighboring Room. Fire does not spread through Closed Doors of Technical Corridors.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 12,
        "Movers": [3,4,5],
        "Direction": 1,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Generator Overheat",
        "RealCardText": "If there is a Malfunction marker in the Generator Room, place a Fire marker in that Room. Place a Fire marker in each Room neighboring a Room with a Fire marker. Fire does not spread through Closed doors or Technical Corridors. If there is no Malfunction marker in the Generator Room, place a Malfunction marker in that Room. Remove this card from the game and reshuffle the Event deck (including discard pile).",
        "AppCardText": "If there is a Malfunction marker in the Generator Room, place a Fire marker in that Room. Place a Fire marker in each Room neighboring a Room with a Fire marker. Fire does not spread through Closed doors or Technical Corridors. If there is no Malfunction marker in the Generator Room, place a Malfunction marker in that Room.",
        "RemoveAndReshuffleDeck": true,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 13,
        "Movers": [2,3],
        "Direction": 2,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Whispers",
        "RealCardText": "Draw another Event card, then place a Noise marker in each Corridor with the same number than the one on this new Evetn card and that is connected to a Room containing a Character. If a Corridor already contains a Noise marker, resolve and Encounter instead. Afterward discard the new Event card without resolving it.",
        "AppCardText": "Place a noise marker in in each Corridor numbered above. If a Corridor already contains a Noise marker, resolve and Encounter instead. ",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": true,
        "SpecialCaseID": 1
    },
    {
        "ID": 14,
        "Movers": [3,4],
        "Direction": 3,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Fear",
        "RealCardText": "Every Character whose Insanity level is higher than the number of cards in their hand is dealt a Contamination card.",
        "AppCardText": "Every Character whose Insanity level is higher than the number of cards in their hand is dealt a Contamination card.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 15,
        "Movers": [2,4,5],
        "Direction": 1,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Monophobia",
        "RealCardText": "Each Character alone in a Room and not in Combat resolves a Panic card.",
        "AppCardText": "Each Character alone in a Room and not in Combat resolves a Panic card.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 16,
        "Movers": [3,4,5],
        "Direction": 4,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Fuel Explosion",
        "RealCardText": "Place a Fire marker in each Engine. Remove this card from the game and reshuffle the Event deck (including discard pile).",
        "AppCardText": "Place a Fire marker in each Engine.",
        "RemoveAndReshuffleDeck": true,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 17,
        "Movers": [2,4,5],
        "Direction": 2,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Terror",
        "RealCardText": "Each Character draws cards from their Action deck until they have 5 cards in hand and then Scans all their Contamination cards. If they have at least 1 INFECTED result, increase their Insanity level to 5. Afterward, all Characters discard all cards from their hands.",
        "AppCardText": "Each Character draws cards from their Action deck until they have 5 cards in hand and then Scans all their Contamination cards. If they have at least 1 INFECTED result, increase their Insanity level to 5. Afterward, all Characters discard all cards from their hands.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 18,
        "Movers": [2,3],
        "Direction": 1,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Ship AI Failure",
        "RealCardText": "If there are at least 2 Malfunction markers in a Room with a Computer, start Self-Destruct sequence. Otherwise, place a Malfunction marker in the Room with the lowest number containing a Computer.",
        "AppCardText": "If there are at least 2 Malfunction markers in a Room with a Computer, start Self-Destruct sequence. Otherwise, place a Malfunction marker in the Room with the lowest number containing a Computer.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    },
    {
        "ID": 19,
        "Movers": [3,4],
        "Direction": 3,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Whispers",
        "RealCardText": "Draw another Event card, then place a Noise marker in each Corridor with the same number than the one on this new Event card and that is connected to a Room containing a Character. If a Corridor already contains a Noise marker, resolve and Encounter instead. Afterward discard the new Event card without resolving it.",
        "AppCardText": "Place a noise marker in in each Corridor numbered above. If a Corridor already contains a Noise marker, resolve and Encounter instead. ",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": true,
        "SpecialCaseID": 3
    },
    {
        "ID": 20,
        "Movers": [2,3],
        "Direction": 3,
        "LarvaMove": false,
        "CreeperMove": "",
        "AdultMove": "",
        "BreederMove": "",
        "Queenmove": "",
        "CardName": "Fear",
        "RealCardText": "Every Character whose Insanity level is higher than the number of cards in their hand is dealt a Contamination card.",
        "AppCardText": "Every Character whose Insanity level is higher than the number of cards in their hand is dealt a Contamination card.",
        "RemoveAndReshuffleDeck": false,
        "ReshuffleBack": false,
        "AlienBagSpecialCase": false,
        "SpecialCaseID": 0
    }
];